## Imports

In [1]:
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 160)

## Load cleaned dataset

In [2]:
PROJECT_ROOT = Path.cwd()

for parent in [PROJECT_ROOT, *PROJECT_ROOT.parents]:
    if (parent / "README.md").exists() and (parent / "data").exists():
        PROJECT_ROOT = parent
        break

DATA_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "cleaned_dataset.csv"
)

if not DATA_PATH.exists():
    raise FileNotFoundError(
        f"Cleaned dataset not found:\n{DATA_PATH}\n"
        "Run Notebook 02 first."
    )

df = pd.read_csv(DATA_PATH)

print("Dataset loaded.")
print(f"Shape: {df.shape}")

Dataset loaded.
Shape: (278701, 39)

In [3]:
display(df.head())
display(df.sample(5, random_state=42))

,composite_key,age_level,gender,bmi_level,smoking,diabetes,age,age_normalized,bmi,hypertension,heart_disease,hba1c_level,glucose,cholesterol,sleep_hours,triglycerides,physical_activity,family_history,stress_level,low_hdl_cholesterol,high_ldl_cholesterol,blood_pressure,high_blood_pressure,sugar_consumption,crp_level,homocysteine_level,systolic_bp,diastolic_bp,alcohol_intake,salt_intake,heart_rate,hdl,ldl,education_level,employment_status,source_dataset,disease_flags,sublabel,label
0,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,9,0.080460,19.20,0.0,0.0,5.8,158.0,214.703704,6.864403,246.703704,High,No,High,Yes,Yes,152.481481,No,Low,8.219098,11.168096,135.380192,89.539936,14.777636,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
1,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,3,0.011494,22.55,0.0,0.0,6.6,159.0,214.703704,6.864403,246.703704,High,No,High,Yes,Yes,152.481481,No,Low,8.219098,11.168096,135.380192,89.539936,14.777636,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
2,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,3,0.011494,22.89,0.0,0.0,4.0,126.0,214.703704,6.864403,246.703704,High,No,High,Yes,Yes,152.481481,No,Low,8.219098,11.168096,135.380192,89.539936,14.777636,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
3,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,3,0.011494,23.12,0.0,0.0,6.2,85.0,214.703704,6.864403,246.703704,High,No,High,Yes,Yes,152.481481,No,Low,8.219098,11.168096,135.380192,89.539936,14.777636,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
4,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,4,0.022989,19.61,0.0,0.0,5.7,155.0,214.703704,6.864403,246.703704,High,No,High,Yes,Yes,152.481481,No,Low,8.219098,11.168096,135.380192,89.539936,14.777636,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal

,composite_key,age_level,gender,bmi_level,smoking,diabetes,age,age_normalized,bmi,hypertension,heart_disease,hba1c_level,glucose,cholesterol,sleep_hours,triglycerides,physical_activity,family_history,stress_level,low_hdl_cholesterol,high_ldl_cholesterol,blood_pressure,high_blood_pressure,sugar_consumption,crp_level,homocysteine_level,systolic_bp,diastolic_bp,alcohol_intake,salt_intake,heart_rate,hdl,ldl,education_level,employment_status,source_dataset,disease_flags,sublabel,label
251858,Middle_Female_Obese_Current_Yes,Middle,Female,Obese,Current,Yes,38,0.413793,34.30,0.142857,0.042857,7.002857,194.0,235.000000,8.400000,75.000000,Moderate,No,High,No,Yes,151.015000,No,Medium,7.461950,12.371993,169.00000,117.000000,25.700000,4.500000,73.000000,59.000000,150.000000,Primary,Employed,hypertension,"1,0,1",DI_HY,Abnormal
76122,Senior_Male_Overweight_Never_Yes,Senior,Male,Overweight,Never,Yes,75,0.839080,25.76,0.000000,0.000000,6.800000,280.0,226.851852,7.336583,246.277778,High,Yes,High,Yes,Yes,148.518519,Yes,Low,6.695729,12.251526,134.40771,89.800234,14.832009,8.418458,75.221963,65.725467,130.405374,Tertiary,Employed,diabetes,"1,0,0",DI,Abnormal
82692,Young_Male_Underweight_Never_No,Young,Male,Underweight,Never,No,10,0.091954,15.92,0.000000,0.000000,4.800000,100.0,228.130653,7.080402,156.115578,Moderate,Yes,Low,No,Yes,150.269231,No,Medium,7.824534,11.846610,133.01005,87.839196,14.957789,8.387940,74.120603,65.713568,131.542714,Tertiary,Employed,diabetes,"0,0,0",N,Normal
155872,Mature_Female_Obese_Former_Yes,Mature,Female,Obese,Former,Yes,67,0.747126,38.20,0.281330,0.117647,6.950128,85.0,189.000000,5.700000,90.000000,Low,No,Medium,No,Yes,150.720942,Yes,High,7.458483,12.384471,158.00000,78.000000,4.700000,3.900000,54.000000,91.000000,159.000000,Secondary,Employed,hypertension,"1,0,1",DI_HY,Abnormal
167837,Middle_Male_Normal_Never_Yes,Middle,Male,Normal,Never,Yes,45,0.494252,22.30,0.133333,0.133333,7.053333,101.0,182.000000,4.400000,232.000000,High,Yes,Low,No,Yes,151.265625,No,Medium,6.948041,12.518972,124.00000,101.000000,6.400000,14.500000,61.000000,72.000000,131.000000,Secondary,Retired,hypertension,"1,0,1",DI_HY,Abnormal

In [4]:
numeric_cols = df.select_dtypes(
    include=np.number
).columns.tolist()

print(f"Numerical columns: {len(numeric_cols)}")

display(
    df[numeric_cols]
    .describe()
    .T
)

Numerical columns: 20

                       count        mean        std         min         25%         50%         75%         max
age                 278701.0   49.710381  21.682385    2.000000   32.000000   50.000000   68.000000   89.000000
age_normalized      278701.0    0.548395   0.249223    0.000000    0.344827    0.551724    0.758620    1.000000
bmi                 278701.0   27.492328   7.068966   10.010000   22.010000   27.320000   32.700000   95.690000
hypertension        278701.0    0.129193   0.187602    0.000000    0.000000    0.071823    0.217063    1.000000
heart_disease       278701.0    0.073945   0.138504    0.000000    0.000000    0.007800    0.117647    1.000000
hba1c_level         278701.0    5.951910   0.952495    3.500000    5.387500    5.800000    6.865766    9.000000
glucose             278701.0  135.267784  38.503495   70.000000  100.000000  137.000000  160.000000  300.000000
cholesterol         278701.0  224.027190  35.668600  150.000000  201.000000  225.000000  243.000000  300.000000
sleep_hours         278701.0    6.954743   1.432179    4.000000    6.196679    6.975185    7.700000   10.000000
triglycerides       278701.0  178.540442  67.344842   50.000000  128.000000  178.000000  241.750000  400.000000
blood_pressure      278701.0  149.893259   4.162959  120.000000  148.946429  149.713320  150.720942  180.000000
crp_level           278701.0    7.488565   1.017615    0.003647    7.294863    7.458483    7.758562   14.997087
homocysteine_level  278701.0   12.463521   0.986776    5.000236   12.287763   12.488407   12.686175   19.999037
systolic_bp         278701.0  134.408557  20.625881   90.000000  125.000000  134.167413  144.000000  179.000000
diastolic_bp        278701.0   89.476008  13.723066   60.000000   83.000000   89.504587   96.000000  119.000000
alcohol_intake      278701.0   15.002295   6.858135    0.000000   11.900000   14.976133   18.000000   30.000000
salt_intake         278701.0    8.480996   2.972729    2.000000    7.200000    8.477600    9.800000   15.000000
heart_rate          278701.0   74.498800  11.449471   50.000000   69.000000   74.487247   80.000000   99.000000
hdl                 278701.0   64.606647  16.003633   30.000000   57.000000   64.650655   72.000000   99.000000
ldl                 278701.0  129.717841  27.463784   70.000000  117.000000  129.882609  142.000000  189.000000

In [5]:
categorical_cols = df.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

print(f"Categorical columns: {len(categorical_cols)}")

categorical_summary = pd.DataFrame({
    "column": categorical_cols,
    "unique_values": [
        df[col].nunique(dropna=False)
        for col in categorical_cols
    ]
})

display(categorical_summary)

/tmp/ipykernel_13975/3710473352.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(

Categorical columns: 19

                  column  unique_values
0          composite_key            192
1              age_level              4
2                 gender              2
3              bmi_level              4
4                smoking              3
5               diabetes              2
6      physical_activity              3
7         family_history              2
8           stress_level              3
9    low_hdl_cholesterol              2
10  high_ldl_cholesterol              2
11   high_blood_pressure              2
12     sugar_consumption              3
13       education_level              3
14     employment_status              3
15        source_dataset              3
16         disease_flags              8
17              sublabel              8
18                 label              2